In [7]:
#記述統計学
#1変量データ
import numpy as np
import scipy as sp

#有効数字指定
%precision 3         

'%.3f'

In [8]:
#データ生成
data = np.array([2,3,3,4,4,4,4,5,5,6])
data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [9]:
#合計
sp.sum(data)

40

In [10]:
#平均値１
N = len(data)
sum_value = sp.sum(data)
mu = sum_value / N
mu

4.000

In [11]:
#平均値２
sp.mean(data)

4.000

In [12]:
#標本分散１
sam_var = sp.sum((data-mu)**2) / N
sam_var

1.200

In [14]:
#標本分散２
sp.var(data,ddof = 0)       #ddof=0にすると標準分散となる

1.200

In [16]:
#不偏分散１
unb_var = sp.sum((data-mu)**2) / (N-1)
unb_var

1.333

In [17]:
#不偏分散２
sp.var(data,ddof = 1)       #ddof=1にすると不偏分散

1.333

In [18]:
#標準偏差１
sta_dev = sp.sqrt(unb_var)
sta_dev

1.155

In [20]:
#標準偏差２
sp.std(data,ddof = 1)

1.155

In [23]:
#標準化
#平均値をゼロにすること(各データから平均値を引く)
#分散を1にする(各データを標準偏差で割る)

stand = (data-mu) / (sp.std(data,ddof = 1))  #不偏偏差で計算
stand

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [24]:
#その他の統計量
#最大値
sp.amax(data)

6

In [25]:
#最小値
sp.amin(data)

2

In [26]:
#中央値
sp.median(data)

4.000

In [27]:
#四分位点
from scipy import stats

In [28]:
#データ生成
data_2 = np.array([1,2,3,4,5,6,7,8,9])

In [30]:
stats.scoreatpercentile(data_2, 75) #75%

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


7.000

In [31]:
stats.scoreatpercentile(data_2, 50) #50%

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


5.000

In [32]:
stats.scoreatpercentile(data_2, 25) #25%

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


3.000

In [20]:
#多変量データ
import pandas as pd
import scipy as sp

%precision 3

'%.3f'

In [3]:
df = pd.DataFrame({'species':['A','A','A','B','B','B'],
                   'length':[2,3,4,6,8,10]})
df

length species
0       2       A
1       3       A
2       4       A
3       6       B
4       8       B
5      10       B

In [5]:
#グループ別の統計量
group = df.groupby('species')
group.mean()

length
species        
A             3
B             8

In [6]:
#標準偏差(母)
group.std(ddof=1)

length
species        
A           1.0
B           2.0

In [7]:
#統計数値一覧
group.describe()

length                                    
         count mean  std  min  25%  50%  75%   max
species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0

In [11]:
#クロス集計表(データ生成)
df_2 = pd.DataFrame({'store':['tokyo', 'tokyo', 'osaka', 'osaka'],
                     'color':['blue', 'red', 'blue', 'red'],
                     'sales':[10,15,13,9]})
df_2
print(df_2)

  color  sales  store
0  blue     10  tokyo
1   red     15  tokyo
2  blue     13  osaka
3   red      9  osaka


In [14]:
#クロス集計表
cross = pd.pivot_table(
    data=df_2,
    values = 'sales',
    aggfunc = 'sum',
    index = 'store',
    columns ='color',
)
print(cross)

color  blue  red
store           
osaka    13    9
tokyo    10   15


In [15]:
#共分散(データ生成)
df_3 = pd.DataFrame({'x':[18.5,18.7,19.1,19.7,21.5,21.7,21.8,22.0,23.4,23.8],
                     'y':[34,39,41,38,45,41,52,44,44,49]})
print(df_3)

      x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45
5  21.7  41
6  21.8  52
7  22.0  44
8  23.4  44
9  23.8  49


In [16]:
#データの取り出し
x = df_3['x']
y = df_3['y']

#サンプルサイズ
N = len(df_3)

#平均値の計算
mu_x = sp.mean(x)
mu_y = sp.mean(y)

In [21]:
#(不偏)共分散
cov_df_3 = sum((x - mu_x) * (y - mu_y)) / N
cov_df_3

6.906

In [22]:
#(母)共分散
cov = sum((x - mu_x) * (y - mu_y)) / (N - 1)
cov

7.673

In [23]:
#分散共分散行列
# cov(x,y) = array([σy2,cov(x,y)]
#                  [cov(x,y),σx2])

In [24]:
#標本共分散
sp.cov(x,y,ddof=0)


array([[ 3.282,  6.906],
       [ 6.906, 25.21 ]])

In [25]:
#不偏共分散
sp.cov(x,y,ddof=1)

array([[ 3.646,  7.673],
       [ 7.673, 28.011]])

In [34]:
#ピアソンの積率相関係数
#不偏分散
sigma_2_x = sp.var(x, ddof = 1)
sigma_2_y = sp.var(y, ddof = 1)

#(不偏分散での)相関係数
cov / sp.sqrt(sigma_2_x * sigma_2_y)

0.759

In [33]:
#標本分散
sigma_2_x_sample = sp.var(x, ddof = 0)
sigma_2_y_sample = sp.var(y, ddof = 0)
#(母分散での)相関係数
cov_df_3 / sp.sqrt(sigma_2_x_sample * sigma_2_y_sample)

0.759

In [35]:
#相関行列
sp.corrcoef(x,y)

array([[1.   , 0.759],
       [0.759, 1.   ]])